###heroku 배포 test
GET https://simsimhaekoon-api-app.herokuapp.com/api/members
###test route test
GET http://localhost:3000/test/members
###login route test
GET http://localhost:3000/login/members


###
POST https://simsimhaekoon-api-app.herokuapp.com/api/members
Content-Type: application/json

{
  "id": 11,
  "name": "Test",
  "team": "engineering",
  "position": "Server Developer",
  "emailAddress": "TEst@google.com",
  "phoneNumber": "010-xxxx-xxxx",
  "admissionDate": "2018/12/10",
  "birthday": "1994/11/08",
  "profileImage": "profile11.png"
}
###
POST http://localhost:3000/test/members
Content-Type: application/json

{
  "id": 11,
  "name": "Test",
  "team": "engineering",
  "position": "Server Developer",
  "emailAddress": "TEst@google.com",
  "phoneNumber": "010-xxxx-xxxx",
  "admissionDate": "2018/12/10",
  "birthday": "1994/11/08",
  "profileImage": "profile11.png"
}

###
POST http://localhost:3000/login/members
Content-Type: application/json

{
  "userId": "TestUser22",
  "pw": "testpw22",
  "name": "Tester22",
  "emailAddress": "TEst22@google.com"
}

###
POST http://localhost:3000/post/post/write
Content-Type: application/json

{
  "userId": "6",
  "name": "6",
  "title": "titleTest9",
  "content": "content test9",
  "viewCount": 0
}

###
PUT https://simsimhaekoon-api-app.herokuapp.com/api/members/1
Content-Type: application/json

  {
    "name": "PUTTest33"
  }
###
PUT http://localhost:3000/test/members/1
Content-Type: application/json

  {
    "name": "PUTTest33"
  }



###
DELETE https://simsimhaekoon-api-app.herokuapp.com/api/members/11
###
DELETE http://localhost:3000/test/members/20
  

###로그인 시도
POST http://localhost:3000/login/signIn
Content-Type: application/json

{
  "userId": "TestUser22",
  "pw": "testpw22"
}

###로그아웃
GET http://localhost:3000/login/logOut

###jwt로그인 시도
POST http://localhost:3000/jwtLogin/signIn
Content-Type: application/json

{
  "userId": "TestUser22",
  "pw": "testpw22"
}

###jwt로그아웃
GET http://localhost:3000/jwtLogin/logOut